FROM trion/ng-cli as builder
USER root
WORKDIR /app
COPY frontend/package.json package.json
COPY frontend/package-lock.json package-lock.json
RUN npm ci  --debug 
COPY frontend/. .
RUN ng build

FROM nginx:alpine
COPY --from=builder  /app/dist/food /usr/share/nginx/html 
COPY frontend/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80