FROM php:8.2-apache

# Apache
ENV APACHE_DOCUMENT_ROOT /var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
RUN sed -ri -e 's!AllowOverride None!AllowOverride All!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
RUN a2enmod rewrite

# PHP Extension
RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable pdo_mysql
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
RUN chmod +x /usr/local/bin/composer

# App
COPY backend /var/www/html
RUN cd /var/www/html && composer update
RUN chown -R www-data /var/www/html && chmod 755 /var/www/html/storage


# CRON
RUN apt-get update && \
    apt-get -y install cron
COPY backend/cron /etc/cron.d/cron
RUN cp /usr/share/zoneinfo/Europe/Zurich /etc/localtime && \
    echo "Europe/Zurich" > /etc/timezone
RUN crontab /etc/cron.d/cron
RUN mkdir -p /var/log/cron

# Custom Entrypoint
COPY backend/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chown www-data /usr/local/bin/entrypoint.sh
RUN chmod a+x /usr/local/bin/entrypoint.sh

WORKDIR /var/www/html/public
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["apache2-foreground"]